appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: Ec/MFgv+NBc0/eYChDLC1AZkhu7odBequObfrPGXqBGM8R7BSMp8JpiwWq7zHN2m1ERPQ/H1/5EGPr52XdCGFHt7YyI7r1vxB5N5NTVxch4l9puraXDIziIRF1rUeXceL4XJFblHq34ATi+qv8Ui9eJExEF9QZHkMjZSCKMfT0ITqP3YnACGjMJD98GCkW6EYDOe9MzQbq0kiwgDBDvJ1HrnZ3E6UzakEAmhDsz64503dYimYMHLQdY6yY8yi1euR4cOz975+dClJ+y3MByRJPblqOYDVoicpOrBaenQ+CvjlJxKNBVFWzwQImOtSCBLd/MWLHT+xc+NDPwQytHmACjM7cMdarznS5XB9KAysOofr5Kru/9CqVBIWpVGmFyhsLU6UGTMfCeu4Xyp/c14wyMFHiYqFTSwm0FfE/Amw4cKaxZI8ZA7niD902tX8zJ2iFfLANuyNPHlS59T0mUedTjjUWcdL7951hf6Ud9ol2Ef8CzUNaOxUOYE04/Qw8UrWH9mBNAjrqLuRBvGlr6FyhIePCWfr6zVKPYNOpilS1FyarbbrzJGS/5kH5BWzMALyl+7Y6HipvrnrOVi1jXajuQlJP6DLFo9HzDvWeLUCbudiYll8D1LHz7D1GpmcWT/V2kHzH+2YiWffVnRLPC9l/M3f+cVLzbbJfoBt04GUBk=
conda_forge_output_validation: false
